---
########
# Argmap environment data
# For use in scripts, layouts and lua code.
# Copyright 2022 Michael Hayes and the mapjs contributors
# SPDX - License - Identifier: MIT
########

# Use ${variable} for referencing other yaml variables, since this is compatible with both bash and pandoc templates.

# Paths

## project
WORKSPACE: ${WORKSPACE}

LIST_FILES_CONFIG:
  - ${PATH_FILE_ENV_ARGMAP} # This file
  - ${PATH_FILE_CONFIG_ARGMAP}
  - ${PATH_FILE_CONFIG_MJS}
  - ${PATH_FILE_ENV_MAPJS}
  - ${PATH_FILE_ENV_ARGMAP_PRIVATE}
  # - ${PATH_FILE_ENV_CONDA}

## conda
CONDA_ENV_ARGMAP: argmap
CONDA_PREFIX: /opt/miniconda3/envs/argmap
PATH_FILE_ENV_CONDA: ${WORKSPACE}/environment-conda-argmap.yml

## web server
DIR_PUBLIC: public
PATH_DIR_PUBLIC: ${PATH_MJS_HOME}/${DIR_PUBLIC}
PORT_DEBUG: 9221
PORT_DEV_SERVER: 9001

## argmap
PATH_DIR_SCRIPTS: ${WORKSPACE}/scripts
PATH_DIR_ARGMAP_SRC: ${WORKSPACE}/src
PATH_FILE_CONFIG_ARGMAP: ${WORKSPACE}/src/config-argmap.yml
PATH_FILE_ENV_ARGMAP: ${WORKSPACE}/environment-argmap.yml # This file
PATH_FILE_ENV_ARGMAP_PRIVATE: ${WORKSPACE}/PRIVATE-environment-argmap.yml

## lua
PATH_DIR_ARGMAP_LUA: ${WORKSPACE}/src/lua
LUA_CPATH: ${WORKSPACE}/lua_modules/lib/lua/5.3/?.so;
LUA_PATH: ${WORKSPACE}/src/lua/?.lua;${WORKSPACE}/lua_modules/share/lua/5.3/?.lua;${WORKSPACE}/lua_modules/share/lua/5.3/?/init.lua;

## mapjs
DIR_MJS: mapjs
PATH_DIR_MJS: ${WORKSPACE}/${DIR_MJS}
PATH_FILE_ENV_MAPJS: ${PATH_DIR_MJS}/environment-mapjs.yml
PATH_FILE_CONFIG_MJS: ${PATH_DIR_MJS}/src/config-mapjs.yml

## layouts
PATH_DIR_LAYOUTS: ${PATH_DIR_ARGMAP_SRC}/layouts
PATH_DIR_INCLUDES: ${PATH_DIR_LAYOUTS}/includes
PATH_DIR_TEMPLATES: ${PATH_DIR_ARGMAP_SRC}/layouts/templates
FILE_TEMPLATE_HTML_ARGMAP_MAIN: ${PATH_DIR_LAYOUTS}/templates/pandoc-mapjs-main-html5.html
PATH_INCLUDES_ARGMAP_CONTAINER: ${PATH_DIR_INCLUDES}/mapjs-map-container.html
PATH_INCLUDES_ARGMAP_CONTROLS: ${PATH_DIR_INCLUDES}/mapjs-widget-controls.html

## pandoc
LANGUAGE_PANDOC: en
PANDOC_DATA_DIR: ${CONDA_PREFIX}/share/pandoc

## Testing
# TODO: Use variable for ${WORKSPACE}/test, /input, /examples, mapjs-json, markdown
INPUT_FILE_YML: ${WORKSPACE}/test/input/example1-clearly-false-white-swan-simplified.yml
INPUT_FILE_YML_NOTES: ${WORKSPACE}/examples/example-2.yml
INPUT_FILE_JSON: ${WORKSPACE}/test/input/mapjs-json/example1-clearly-false-white-swan-simplified.json
INPUT_FILE_MD0: ${WORKSPACE}/test/input/markdown/example1-clearly-false-white-swan-simplified-0mapjs.md
INPUT_FILE_MD: ${WORKSPACE}/test/input/markdown/example1-clearly-false-white-swan-simplified-1mapjs.md
INPUT_FILE_MD2: ${WORKSPACE}/test/input/markdown/example1-clearly-false-white-swan-simplified-2mapjs.md
INPUT_FILE_MD_META: ${WORKSPACE}/test/input/markdown/example1-clearly-false-white-swan-simplified-meta-mapjs.md
INPUT_FILE_JSON2: ${WORKSPACE}/test/input/mapjs-json/example2-clearly-false-white-swan-v3.mup
INPUT_FILE_JSON_LINKS: ${WORKSPACE}/test/input/mapjs-json/example1-clearly-false-white-swan-simplified-with-links.json
PATH_INPUT_FILE_HTML: '$(realpath --no-symlinks --relative-to: "${PATH_DIR_PUBLIC}" "${PATH_DIR_PUBLIC}/input/example1-clearly-false-white-swan-simplified.html")' # QUESTION: Does this value need double quoting because it contains : ?
PATH_OUTPUT_FILE_HTML: '$(realpath --no-symlinks --relative-to: "${PATH_DIR_PUBLIC}" "${PATH_DIR_PUBLIC}/output/html/example1-clearly-false-white-swan-simplified.html")' # QUESTION: Does this value need double quoting because it contains : ?

## external to project
PATH_MISC_DEV: ${DIR_PROJECTS}/misc
PATH_CHROME_PROFILE_DEBUG: ${PATH_MISC_DEV}/chrome-debug-argmap
PATH_TEST_LOG: "${PATH_MISC_DEV}/tests_output.txt"
DEFAULT_DIFF_FILENAME: ${DIR_PROJECTS}/mapjs-git-bisect/diffs/all_mapjs_fixes_latest_modified.diff

## Not used, but for reference:
DIR_PROJECTS: $(dirname "${WORKSPACE}") # Needed for scripts/argmap.env tmp chrome profile

# Automatically listed (but not complete) ()
#   from: https://askubuntu.com/questions/1182024/how-to-display-all-new-variables-after-terminal-started#answer-1182025

# Deprecated
PATH_MJS_HOME: ${PATH_DIR_MJS}
ENV_FILE: ${WORKSPACE}/environment.yml
PATH_FILE_CONDA_ENV: ${WORKSPACE}/environment-conda-argmap.yml
