---
########
# MAPJS config data
# For use in mapjs code, layouts and pandoc filters.
# Copyright 2022 Michael Hayes and the mapjs contributors
# SPDX - License - Identifier: MIT
########

# Template Elements

# Values representing html classes, ids etc should be kebab case
#   MAP_INSTANCE_ID and ${path-json-source} are populated dynamically by pandoc.

argmap_collection:
  tag: article
  class: argmap-collection
argmap_grouping:
  tag: article
  class: argmap
  parent: argmap_collection

mapjs_instance:
  tag: div
  class: mapjs-app
  parent: mapjs_grouping
mapjs_map:
  id: ${mapjs_map.id-prefix}${MAP_INSTANCE_ID}
  id-prefix: container-
  tag: div
  class: mapjs-container
  parent: mapjs_app
mapjs_src_data:
  tag: script
  class: argmap-json
  src: ${path-json-source}
  parent: mapjs_map

mapjs_control:
  id: ${mapjs_control.id-prefix}${MAP_INSTANCE_ID}
  id-prefix: menubar-mapjs-
  tag: div
  class: menubar-mapjs
  role: menubar
  parent: mapjs_instance
toolbar_main:
  tag: div
  class: toolbar-mapjs-main
  role: toolbar
  aria_label: Edit nodes
  parent: mapjs_control
toolbar_edit_links:
  id: ${toolbar_edit_links.id-prefix}${MAP_INSTANCE_ID}
  id-prefix: toolbar-edit-links-
  tag: div
  class: toolbar-mapjs-edit-links
  role: toolbar
  aria_label: Edit links
  parent: mapjs_control
toolbar_fileButton:
  class: readFile

# Map elements

node:
  class: mapjs-node
connector:
  class: mapjs-connector
...
