---
########
# Mapjs environment data - DEFAULTS
# Copy this to mapjs/config/environment-mapjs.yaml and customise as you wish
# For use in scripts and js code
# Copyright 2022 Michael Hayes
# SPDX - License - Identifier: MIT
########

# Use ${variable} for referencing other yaml variables

# Variables
PATH_DIR_ROOT_MAPJS: ${WORKSPACE}

## Config files
PATH_DIR_CONFIG_MAPJS: ${PATH_DIR_MJS}/${DIR_CONFIG}
PATH_FILE_ENV_MAPJS: ${PATH_DIR_CONFIG_MAPJS}/environment-mapjs.yml
PATH_FILE_CONFIG_MJS: ${PATH_DIR_CONFIG_MAPJS}/config-mapjs.yml
PATH_DIR_CONFIG_MAPJS_PROCESSED: ${PATH_DIR_CONFIG_MAPJS}/${DIR_PROCESSED}
PATH_FILE_CONFIG_MJS_PROCESSED: ${PATH_DIR_CONFIG_MAPJS_PROCESSED}/config-mapjs-processed.yaml

## dev webserver values
DIR_HTML_SERVER_OUTPUT: output

## These are absolute paths, for reading/writing to the correct directory
# TODO this file needs to work in both mapjs and argmap. So should probably avoid referring to WORKSPACE since that
DIR_HTML: ${WORKSPACE}/test
DIR_PUBLIC_OUTPUT: ${DIR_HTML}/${DIR_HTML_SERVER_OUTPUT} # Test output folder
DIR_HTML_INPUT: ${DIR_HTML}/input                        # Test input folder

## For html links, use relative paths (to test/output folder) - more portable
DIR_MJS_JSON: mapjs-json
PATH_DIR_MJS_SRC_JS: ${PATH_MJS_HOME}/src
PATH_DIR_PUBLIC_MJS_JSON: ${DIR_PUBLIC_OUTPUT}/${DIR_MJS_JSON}
PATH_MJS_HTML_DIST_TAGS: ${PATH_DIR_INCLUDES}
PATH_LOG_FILE_EXPECT: /home/s6mike/git_projects/mapjs-git-bisect/expect_log.txt
PATH_BISECT_PATCH_FILE: ${DIR_PROJECTS}/mapjs-git-bisect/diffs/all_mapjs_fixes_latest.diff
PATH_REPLAY_SCRIPT: ${WORKSPACE}/test/devtools-recordings/argmap-add-child.json
PATH_REPLAY_SCRIPT_ADD_IDEA: ${WORKSPACE}/test/devtools-recordings/argmap-add-child.json
PATH_REPLAY_SCRIPT_NODE_CLICK: ${WORKSPACE}/test/devtools-recordings/argmap-node-click.json
PATH_REPLAY_SCRIPT_BUTTON_UNDO_REDO: ${WORKSPACE}/test/devtools-recordings/argmap-button-undo-redo.json
PATH_REPLAY_SCRIPT_BUTTON_ADD_LINK: ${WORKSPACE}/test/devtools-recordings/argmap-button-add-link.json
PATH_REPLAY_SCRIPT_EDIT_FIRST_CHILD: ${WORKSPACE}/test/devtools-recordings/argmap-edit-first-child.json
PATH_REPLAY_SCRIPT_KEYS_UNDO_REDO: ${WORKSPACE}/test/devtools-recordings/argmap-keys-undo-redo.json
PATH_REPLAY_SCRIPT_ADD_ROOT_PARENT: ${WORKSPACE}/test/devtools-recordings/argmap-add-root-parent.json
PATH_REPLAY_SCRIPT_ADD_SUPPORTING: ${WORKSPACE}/test/devtools-recordings/argmap-add-supporting-group.json
PATH_REPLAY_SCRIPT_ADD_SUPPORTING_E2V3: ${WORKSPACE}/test/devtools-recordings/argmap-add-supporting-group-e2v3.json
PATH_REPLAY_SCRIPT_EDIT_LINK_EXISTING: ${WORKSPACE}/test/devtools-recordings/argmap-edit-existing-link.json
PATH_REPLAY_SCRIPT_BUTTON_ZOOM: ${WORKSPACE}/test/devtools-recordings/argmap-button-zoom-in-out.json
PATH_REPLAY_SCRIPT_KEYS_ZOOM: ${WORKSPACE}/test/devtools-recordings/argmap-keys-zoom-in-zoom-reset.json
PATH_REPLAY_SCRIPT_DELETE_GRANDCHILD: ${WORKSPACE}/test/devtools-recordings/argmap-delete-grandchild.json
PATH_REPLAY_SCRIPT_EDIT_LINK_NEW: ${WORKSPACE}/test/devtools-recordings/argmap-edit-new-link.json
PATH_REPLAY_SCRIPT_EDIT_LINK_EXISTING_ALL_ATTRIBUTES: ${WORKSPACE}/test/devtools-recordings/argmap-edit-existing-link-all-attributes.json
PATH_REPLAY_SCRIPT_BUTTON_EDITLINK_ERROR: ${WORKSPACE}/test/devtools-recordings/mapjs-button-editlink-menu-error.json
PATH_REPLAY_SCRIPT_MOUSE_PAST_EDITLINK: ${WORKSPACE}/test/devtools-recordings/mapjs-mouse-past-linkEditWidget-after-link-click.json

...
