---
########
# Mapjs environment data - DEFAULTS
# Copy this to mapjs/config/environment-mapjs.yaml and customise as you wish
#   So this file IS considered part of the public API for this app and changing variable names etc will be considered BREAKING.
# For use in scripts and js code
# Copyright 2022 Michael Hayes
# SPDX - License - Identifier: MIT
########

# Use ${variable} for referencing other yaml variables

# Variables
PATH_DIR_MAPJS_ROOT: ${PATH_DIR_MAPJS}
WORKSPACE: ${PATH_DIR_ARGMAP_ROOT}

## dev webserver values
DIR_HTML_SERVER_OUTPUT: output

## These are absolute paths, for reading/writing to the correct directory
DIR_HTML: ${PATH_DIR_ARGMAP_ROOT}/test
DIR_PUBLIC_OUTPUT: ${DIR_HTML}/${DIR_HTML_SERVER_OUTPUT} # Test output folder
DIR_HTML_INPUT: ${DIR_HTML}/input                      # Test input folder

...
