---
########
# Argmap config data
# For use in lua code, layouts and scripts.
# Copyright 2022 Michael Hayes and the mapjs contributors
# SPDX - License - Identifier: MIT
########

# Argmap document metadata
DEFAULT_LANGUAGE: en
MAPJS_CSS: &MAPJS_CSS /mapjs-default-styles.css

# All CSS files used by html output.
#   However, pandoc templates won't expand the variables
#   , so need to reference anchor earlier in same doc instead.
css: # Default pandoc template value
  - ${MAPJS_CSS}

# DEPRECATED

lang: en

...
