---
########
# Argmap config data
# For use in lua code, layouts and scripts.
# Copyright 2022 Michael Hayes and the mapjs contributors
# SPDX - License - Identifier: MIT
########

# Argmap document metadata
DEFAULT_LANGUAGE: en
FILE_TEMPLATE_HTML_DEFAULT: ${FILE_TEMPLATE_HTML_ARGMAP_MAIN}
DEFAULT_MAPJS_CSS: /mapjs-default-styles.css

# All CSS files used by html output.
#   However, pandoc templates won't expand the variables
#   , so need to reference anchor earlier in same doc instead.
css: # Default pandoc template value
  - ${DEFAULT_MAPJS_CSS}

# DEPRECATED

lang: en
MAPJS_CSS: ${DEFAULT_MAPJS_CSS}

...
