---
########
# Argmap environment data
# For use in scripts, layouts and lua code.
# Copyright 2022 Michael Hayes and the mapjs contributors
# SPDX - License - Identifier: MIT
########

# Use ${variable} for referencing other yaml variables, since this is compatible with both bash and pandoc templates.

# Paths

## project
WORKSPACE: /home/s6mike/git_projects/argmap

## config
DIR_CONFIG: config
PATH_DIR_CONFIG_ARGMAP: ${WORKSPACE}/${DIR_CONFIG}
DIR_PROCESSED: processed
# TODO: rename as PATH_DIR_CONFIG_ARGMAP_PROCESSED
PATH_DIR_CONFIG_PROCESSED: ${PATH_DIR_CONFIG_ARGMAP}/${DIR_PROCESSED}

# Processed config files are at top, so their results are used ahead of raw config files
# QUESTION: Just check two config folders instead?

LIST_FILES_CONFIG_INPUT:
- ${PATH_FILE_ENV_ARGMAP} # This file
- ${PATH_FILE_CONFIG_ARGMAP}
- ${PATH_FILE_CONFIG_MJS}
- ${PATH_FILE_ENV_MAPJS}
- ${PATH_FILE_ENV_ARGMAP_PRIVATE}
# - ${PATH_FILE_ENV_CONDA}

# Not needed here because bash function generates this list. However, might be needed for other apps?
# LIST_FILES_CONFIG_PROCESSED:
# - ${PATH_FILE_ENV_ARGMAP_PROCESSED}
# - ${PATH_FILE_CONFIG_ARGMAP_PROCESSED}
# - /home/s6mike/git_projects/argmap/config/processed/PRIVATE-environment-argmap-processed.yaml
# - /home/s6mike/git_projects/argmap/mapjs/config/processed/config-mapjs-processed.yaml
# - /home/s6mike/git_projects/argmap/mapjs/config/processed/environment-mapjs-processed.yaml
# # - ${PATH_FILE_CONFIG_PROCESSED_VARIABLES}

## conda
CONDA_ENV_ARGMAP: argmap
CONDA_PREFIX: /opt/miniconda3/envs/argmap
PATH_FILE_ENV_CONDA: ${PATH_DIR_CONFIG_ARGMAP}/environment-conda-argmap.yml

## web server
DIR_PUBLIC: public
PATH_DIR_PUBLIC: ${PATH_MJS_HOME}/${DIR_PUBLIC}
PORT_DEBUG: 9221
PORT_DEV_SERVER: 9001

## argmap
PATH_DIR_SCRIPTS: ${WORKSPACE}/scripts
PATH_DIR_ARGMAP_SRC: ${WORKSPACE}/src
PATH_FILE_CONFIG_ARGMAP: ${PATH_DIR_CONFIG_ARGMAP}/config-argmap.yml
PATH_FILE_ENV_ARGMAP: ${PATH_DIR_CONFIG_ARGMAP}/environment-argmap.yml # This file
PATH_FILE_ENV_ARGMAP_PRIVATE: ${PATH_DIR_CONFIG_ARGMAP}/PRIVATE-environment-argmap.yml
PATH_FILE_PANDOC_DEFAULT_CONFIG_PREPROCESSOR: ${PATH_DIR_CONFIG_ARGMAP}/pandoc-defaults-config-preprocessor.yml
PATH_FILE_ENV_ARGMAP_PROCESSED: ${PATH_DIR_CONFIG_PROCESSED}/environment-argmap-processed.yaml
PATH_FILE_CONFIG_ARGMAP_PROCESSED: ${PATH_DIR_CONFIG_PROCESSED}/config-argmap-processed.yaml

## lua
PATH_DIR_ARGMAP_LUA: ${WORKSPACE}/src/lua
LUA_CPATH: ${WORKSPACE}/lua_modules/lib/lua/5.3/?.so;
LUA_PATH: ${WORKSPACE}/src/lua/?.lua;${WORKSPACE}/lua_modules/share/lua/5.3/?.lua;${WORKSPACE}/lua_modules/share/lua/5.3/?/init.lua;

## mapjs
DIR_MJS: mapjs
PATH_DIR_MJS: ${WORKSPACE}/${DIR_MJS}

## layouts
PATH_DIR_LAYOUTS: ${PATH_DIR_ARGMAP_SRC}/layouts
PATH_DIR_INCLUDES: ${PATH_DIR_LAYOUTS}/includes
PATH_DIR_TEMPLATES: ${PATH_DIR_ARGMAP_SRC}/layouts/templates
FILE_TEMPLATE_HTML_ARGMAP_MAIN: ${PATH_DIR_LAYOUTS}/templates/pandoc-mapjs-main-html5.html
PATH_INCLUDES_ARGMAP_CONTAINER: ${PATH_DIR_INCLUDES}/mapjs-map-container.html
PATH_INCLUDES_ARGMAP_CONTROLS: ${PATH_DIR_INCLUDES}/mapjs-widget-controls.html

## pandoc
PANDOC_DATA_DIR: ${CONDA_PREFIX}/share/pandoc

## Testing
# TODO: Add variables for ${WORKSPACE}/test, /input, /examples, mapjs-json, markdown
INPUT_FILE_YML: ${WORKSPACE}/test/input/example1-clearly-false-white-swan-simplified.yml
INPUT_FILE_YML_NOTES: ${WORKSPACE}/examples/example-2.yml
INPUT_FILE_JSON: ${WORKSPACE}/test/input/mapjs-json/example1-clearly-false-white-swan-simplified.json
INPUT_FILE_MD0: ${WORKSPACE}/test/input/markdown/example1-clearly-false-white-swan-simplified-0mapjs.md
INPUT_FILE_MD: ${WORKSPACE}/test/input/markdown/example1-clearly-false-white-swan-simplified-1mapjs.md
INPUT_FILE_MD2: ${WORKSPACE}/test/input/markdown/example1-clearly-false-white-swan-simplified-2mapjs.md
INPUT_FILE_MD_META: ${WORKSPACE}/test/input/markdown/example1-clearly-false-white-swan-simplified-meta-mapjs.md
INPUT_FILE_JSON2: ${WORKSPACE}/test/input/mapjs-json/example2-clearly-false-white-swan-v3.mup
INPUT_FILE_JSON_LINKS: ${WORKSPACE}/test/input/mapjs-json/example1-clearly-false-white-swan-simplified-with-links.json
PATH_FILE_OUTPUT_EXAMPLE: ${WORKSPACE}/test/output/html/example1-clearly-false-white-swan-simplified.html 

# DEPRECATE?
PATH_URL_INPUT_FILE_EXAMPLE: input/example1-clearly-false-white-swan-simplified.html

## External to project
DIR_PROJECTS: /home/s6mike/git_projects
PATH_MISC_DEV: ${DIR_PROJECTS}/misc
PATH_CHROME_PROFILE_DEBUG: ${PATH_MISC_DEV}/chrome-debug-argmap
PATH_TEST_LOG: "${PATH_MISC_DEV}/tests_output.txt"
DEFAULT_DIFF_FILENAME: ${DIR_PROJECTS}/mapjs-git-bisect/diffs/all_mapjs_fixes_latest_modified.diff

# DEPRECATED
PATH_URL_OUTPUT_FILE_EXAMPLE: output/html/example1-clearly-false-white-swan-simplified.html 
PATH_MJS_HOME: ${PATH_DIR_MJS}
ENV_FILE: ${WORKSPACE}/environment.yml
PATH_FILE_CONDA_ENV: ${WORKSPACE}/environment-conda-argmap.yml
PATH_OUTPUT_FILE_HTML: ${PATH_URL_OUTPUT_FILE_EXAMPLE}
PATH_INPUT_FILE_HTML: ${PATH_URL_INPUT_FILE_EXAMPLE}

